# Generated by Django 6.0 on 2025-12-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alert_system', '0003_alertassignment_hospital_policestation_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='status',
        ),
    ]
