# Generated by Django 6.0 on 2025-12-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alert_system', '0005_alter_userlocation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicePublicAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='missing_persons/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alert_system.policestation')),
            ],
        ),
    ]
