# Generated by Django 6.0 on 2025-12-23 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alert_system', '0006_policepublicalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='public_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alert_system.policepublicalert'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
